export const UPLOAD_PHOTO_HOLDNG_ID_IN_PROGRESS = "UPLOAD_PHOTO_HOLDNG_ID";
export const UPLOAD_PHOTO_HOLDNG_ID_ERROR = "UPLOAD_PHOTO_HOLDNG_ID_ERROR";
export const UPLOAD_PHOTO_HOLDNG_ID_SUCCESS = "UPLOAD_PHOTO_HOLDNG_ID_SUCCESS";

export const UPLOAD_PASSPORT_IN_PROGRESS = "UPLOAD_PASSPORT_IN_PROGRESS";
export const UPLOAD_PASSPORT_ERROR = "UPLOAD_PASSPORT_ERROR";
export const UPLOAD_PASSPORT_SUCCESS = "UPLOAD_PASSPORT_SUCCESS";

export const UPLOAD_LICENSE_IN_PROGRESS = "UPLOAD_LICENSE_IN_PROGRESS";
export const UPLOAD_LICENSE_ERROR = "UPLOAD_LICENSE_ERROR";
export const UPLOAD_LICENSE_SUCCESS = "UPLOAD_LICENSE_SUCCESS";

export const FACE_MATCH_IN_PROGRESS = "FACE_MATCH_IN_PROGRESS";
export const FACE_MATCH_ERROR = "FACE_MATCH_ERROR";
export const FACE_MATCH_SUCCESS = "FACE_MATCH_SUCCESS";

export const DETAILS_MATCH_IN_PROGRESS = "DETAILS_MATCH_IN_PROGRESS";
export const DETAILS_MATCH_ERROR = "DETAILS_MATCH_ERROR";
export const DETAILS_MATCH_SUCCESS = "DETAILS_MATCH_SUCCESS";

export const VALIDATION_STARTED = "VALIDATION_STARTED";

// export const DOB_MATCH_IN_PROGRESS = "DOB_MATCH_IN_PROGRESS";
// export const DOB_MATCH_ERROR = "DOB_MATCH_ERROR";
// export const DOB_MATCH_SUCCESS = "DOB_MATCH_SUCCESS";

// export const GENDER_MATCH_IN_PROGRESS = "GENDER_MATCH_IN_PROGRESS";
// export const GENDER_MATCH_ERROR = "GENDER_MATCH_ERROR";
// export const GENDER_MATCH_SUCCESS = "GENDER_MATCH_SUCCESS";

export const VALIDATION_COMPLETE = "VALIDATION_COMPLETE";