export const UPLOAD_PHOTO_HOLDNG_ID = "UPLOAD_PHOTO_HOLDNG_ID";
export const UPLOAD_DRIVERS_LICENSE = "UPLOAD_DRIVERS_LICENSE";
export const UPLOAD_PASSPORT = "UPLOAD_PASSPORT";
export const VALIDATE = "VALIDATE";
export const VALIDATING_PASSPORT_INPROGRESS = "VALIDATING_PASSPORT_INPROGRESS";
export const VALIDATING_PHOTO_AND_ID_IN_PROGRESS = "VALIDATING_PHOTO_AND_ID_IN_PROGRESS";
export const VALIDATING_LICENSE_IN_PROGRESS = "VALIDATING_LICENSE_IN_PROGRESS";

export const FACE_MATCH = "FACE_MATCH";
export const NAME_MATCH = "NAME_MATCH";
export const DOB_MATCH = "DOB_MATCH";
export const GENDER_MATCH = "GENDER_MATCH";

export const VALIDATION_IN_PROGRESS = "VALIDATION_IN_PROGRESS";
export const VALIDATION_HAS_ERRORED = "VALIDATION_HAS_ERRORED";
export const VALIDATION_SUCCESS = "VALIDATION_SUCCESS";